repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.17
    hooks:
      - id: uv-lock

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: /opt/venv/bin/pytest --tb=short -q
        language: system
        pass_filenames: false
        files: ^(rnavigate|tests)/

      - id: sphinx
        name: sphinx
        entry: /opt/venv/bin/sphinx-build docs/source docs/build/html -D nbsphinx_execute=never
        language: system
        pass_filenames: false
        files: ^docs/
